# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'capybara/rspec'
require 'selenium-webdriver'
require 'selenium'

#Capybara.default_driver = :selenium

Capybara.default_driver = :selenium

browser = ENV['BROWSER_TYPE']

if browser == 'firefox'

	Capybara.register_driver :firefox do |app|
		Capybara::Selenium::Driver.new(app, :browser => :firefox)
	end

  Capybara.default_driver = :firefox

elsif browser == 'chrome'

	Capybara.register_driver :selenium_chrome do |app|
  	Capybara::Selenium::Driver.new(app, :browser => :chrome)
	end

  Capybara.default_driver = :selenium_chrome

elsif browser == 'ie'

  capabilities = Selenium::WebDriver::Remote::Capabilities.new
  capabilities[:ignoreProtectedModeSettings] = true
  capabilities[:javascriptEnabled] = true
  capabilities[:cssSelectorsEnabled] = true
  capabilities[:acceptSslCerts] = true

  Capybara.register_driver :selenium_ie do |app|
    Capybara::Selenium::Driver.new(app, :browser => :internet_explorer, 
                                        :desired_capabilities => capabilities)
  end

  Capybara.default_driver = :selenium_ie

end

Capybara.run_server = false

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
end

def alert_present?
  begin
    page.driver.browser.switch_to.alert
    return true
  rescue
    return false
  end
end